### ISSUE TITLE
We need to define our presubmission process

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/governance#1]
Hey all. Just a note that we should define a presubmission process for packages given we already have a bit of interest - [see here](https://github.com/pyOpenSci/pyApiToolkit/issues/1). 

Along with that we will need to have some language somewhere in the organization that directs folks to where we'd like them to submit presubmission issues!

**Comment by simkimsia** [comment]
Following this issue

**Comment by lwasser** [comment]
sounds great @simkimsia we are talking with rOpenSci and will likely adopt their process but need to define it more clearly. More to come! Thank you for for keeping tabs on this process and for your patience!

**Comment by lwasser** [comment]
closing this as we have a presubmission process now!  in our pyopensci/software-review repository
