### ISSUE TITLE
BoF Submission

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/governance#10]
@choldgraf since we don't have a discuss forum yet... can i list you as the backup moderator for our BoF this summer (fully understanding you may not end up attending?). We can also substitute if needbe.
Doc: 
https://docs.google.com/document/d/1UlKxVaDalT9sJUa2dcOM7Ea1It6k5h5r66JSpu5rW3I/edit

**Comment by choldgraf** [comment]
yep

**Comment by lwasser** [comment]
hi @choldgraf just running through old issues and closing!! THANK YOU so much for supporting us here! it's so funny to think about those early days of the project vs now building it as an organization!! cheers!
