### ISSUE TITLE
Convert this repository into the "master" repo

### ISSUE THREAD

**Issue by choldgraf** [pyOpenSci/governance#15]
It looks like when this repository was created, we made it a "fork" from the pyopenscience organization. Making it a fork instead of a total copy causes GitHub to behave in weird ways, so we should figure out how to make this repository the "master" repository.

I tried deleting the old pyopenscience governance repo, and it then switched @jlpalomino 's governance repo to be the "master" one haha. We can either:

* Systematically delete each person's fork of the governance repo until GitHub decides the "next in line" is the pyopensci one
* Completely copy this repo into a new repository, then rename this one and the new one so that the new one is called "governance", then move over the issues

Thoughts?

**Comment by lwasser** [comment]
i think this is no longer a fork as it was removed from the original repo! so we can close it now!! hi and thanks @choldgraf  :)
