### ISSUE TITLE
Discourse link is broken

### ISSUE THREAD

**Issue by astrojuanlu** [pyOpenSci/governance#16]
Hi! I just found a Discourse link on https://www.pyopensci.org/get-involved-contact/ but it appears to be broken: https://pyopensci.discourse.group/ does it still exist?

**Comment by lwasser** [comment]
Ok i am going to remove discourse link from the website...  as we just don't use it and it keeps getting shut down. I am going to leave it shut down and will think about whether we really need it for the time being... i think discussions in github could be fine for now. Why maintain something that we aren't using.  thank you for posting this @astrojuanlu

**Comment by astrojuanlu** [comment]
Yeah, probably GitHub Discussions is fine. Thanks @lwasser! Feel free to close the issue or leave it open

**Comment by lwasser** [comment]
thanks @astrojuanlu !! i'll close it once I update the website which hopefully will be today :) Grateful for you issue submission here !! thank you!

**Comment by lwasser** [comment]
this has been fixed!
