### ISSUE TITLE
Getting involved in pyOpenSci

### ISSUE THREAD

**Issue by Athene-ai** [pyOpenSci/governance#17]
Hi @lwasser

I would like get involved in building pyOpenSci and in particular helping with technical infrastructure.

How is it possible?

**Comment by lwasser** [comment]
ih @Athene-ai !! thank you for reaching out. we'd love help but are. just getting going. what type of skills do you have / or interests? i can think about this more ... so appreciative of your reaching out and so sorry it took me so long to respond here!!

**Comment by Athene-ai** [comment]
Hi @lwasser
I have github and phython experiences . I have also editor and organisational skills

**Comment by lwasser** [comment]
awesome. Ok @Athene-ai let me think about things we might need help with and I will get back to you. i really appreciate your reaching out. 🙌

**Comment by Athene-ai** [comment]
@lwasser perfect and I can not wait to start working with you all 😉

**Comment by lwasser** [comment]
Good morning @Athene-ai 👋 i haven't forgotten about you!! i just needed a bit of time to get organized. I am slowly pulling together lists of things that we need help with and putting them in our [project here](https://github.com/orgs/pyOpenSci/projects/3). this is a test to see if that is a good way to help folks see what we could use help with. SO if you wish, you can keep tabs on that project (please let me know if you can view it without issue) and respond to an issue if there is something that seems like a task you'd like to take on. I will be slowly adding information to that project over the next few weeks so stay tuned! 

I'm open to feedback regarding the best way to post things we could use help with! thank you again for being here.

**Comment by Athene-ai** [comment]
Hi @lwasser !

thanks for the information but I have issue to view the project page

Let me know

**Comment by lwasser** [comment]
oh ok - so you can't see it? Let me play with permissions and see if i can figure that out. Thank you for letting me know!

**Comment by Athene-ai** [comment]
_so you can't see it? _ --> right

_Let me play with permissions and see if i can figure that out_ --> Thanks because I want to get involved ;-)
_Thank you for letting me know!_ --> the pleasure is mine!

**Comment by lwasser** [comment]
OK! i think i fixed the permissions on the project. can you kindly try again?
Right now there is only one issue that is open but i plan to add a few more this week. we have a combination of needs from going through peer reviews and pulling out information into a table (could be automated with python / github API or could be done manually. to adding CI to projects...  So please know i'll be adding a few more items over the next week if the one that is open isn't a good fit!

**Comment by lwasser** [comment]
hi there @Athene-ai i'm closing this issue. however feel free to reach out to us on [discourse](https://pyopensci.discourse.group/)  or elsewhere if you have questions, want to work on something etc!
