### ISSUE TITLE
I'm looking for some mentorship

### ISSUE THREAD

**Issue by pljspahn** [pyOpenSci/governance#22]
Hello Leah

I recently attended a conference in Longmont where I was introduced to Species Distribution Modeling. I have a CS background and work locally in the nursery industry, and in the last few weeks I have been brainstorming how I could use such a tool.

I don't have a formal education in ecology or data science, but I have been watching some videos and going through some tutorials on how SDM works. I have a long-term open source project (https://github.com/pljspahn/hortus-mundus) that has been bobbing around in my head for several years and learning about SDM has given me the motivation to start working on it. I have nothing of value there at the moment outside of a simple outline.

Searching around various CS/CSU websites sent me down a bit of a rabbit hole where I was able to find out about pyOpenSci and the work you've done with Earth Lab, so I'm hoping you'll be able to give me some guidance on how I might go about finding someone that can help me learn how to build my first SDM so I can better understand the process and allow me to continue adding new models over time. Maybe you know of a capable grad student or colleague that would be interested in meeting in person/online that would be able to shove me into the proverbial fire? 

I wasn't sure the best way to reach out to you, so I'm doing it here and I hope that's okay.

Thanks for your time

Preston

**Comment by lwasser** [comment]
Hey @pljspahn gosh i'm not sure. Have you reached out to anyone maybe in the ecology / biology department at CU? I'm afraid i dont know anyone specifically. but i'm going to ping a colleague here @mbjoseph in case they might know someone in those departments who could direct you / mentor you on species distribution modeling. or just a person in general who does that type of modeling. Max any ideas? 

 I'm sorry that I can't be of more help - that is not a science domain i'm super familiar with.

**Comment by lwasser** [comment]
this has been quiet for almost a week so I am closing it.
