### ISSUE TITLE
Jupyter books for pyopensci docs

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/governance#4]
hey @choldgraf @kysolvik and i are starting to port over the docs from ropensci to pyopensci!!. didn't you setup a repo (predicablly noisy maybe) that facilitated an automagic online "book" creation from a series of notebooks? 

We'd like to create something like this

https://ropensci.github.io/dev_guide/collaboration.html  
for our pyopensci guide. i'm not sure that we need to have notebooks for this as it's all text but we do want to create an online guide. Is your repo something we could use? / fork add here to create a new book for our guidelines?

**Comment by choldgraf** [comment]
indeed that repo now is within the jupyter org itself:  https://github.com/jupyter/jupyter-book

here's an example:  https://jupyter.org/jupyter-book

**Comment by lwasser** [comment]
awesome! @choldgraf  do you suggest we just fork the repo from jupyter ? Also could we just write the entire thing in markdown given we don't actually need notebooks and that would be lighter weight? ie no need for build scripts !! This is perfect!! @kysolvik is going to use hackmd to pull together the docs from ropensci. boy would it be nice to just port from hackmd to github and have content ready and online!!

**Comment by choldgraf** [comment]
I recommend following the guide here to get it set up :-) https://jupyter.org/jupyter-book/guide/01_overview

**Comment by choldgraf** [comment]
sure thing!

**Comment by lwasser** [comment]
thank you so much @choldgraf  !! so appreciative!! :)

**Comment by choldgraf** [comment]
@lwasser here's the site: https://pyopensci.github.io/dev_guide/

I only copied some of the text from the one page you linked just to show how it looks. To add more content, do the following:

1. In the `dev_guide` repo of this org...
2. Add markdown files to the `content/` folder
3. Add an entry to `_data/toc.yaml` that points to the new content.
4. Run `make book`
5. Push to the master branch (or run make serve to preview locally, if you have jekyll installed)

BTW - jupyter book is still iterating rapidly, and I'd love to have feedback about how to make it more user friendly (e.g. I've been playing around with make it use a purely command-line interface, though am still unsure if that's a good idea)

**Comment by lwasser** [comment]
this is amazing @choldgraf  THANK YOU for doing it so quickly. @kysolvik have a look at the link above! We will absolutely give you feedback on this as we build things . THANK YOU THANK YOU THANK YOU!!

**Comment by kysolvik** [comment]
Wow, this is awesome! Thanks so much @choldgraf! I'll let you know if I have questions as we start adding to it, but it sounds pretty straightforward and the book looks really clean

**Comment by kysolvik** [comment]
Closing bc our dev guide is up and running! https://www.pyopensci.org/dev_guide/intro
