### ISSUE TITLE
Give @kierisi write access for this repo

### ISSUE THREAD

**Issue by willingc** [pyOpenSci/governance#52]
@lwasser CODEOWNERS file is showing an error since @kierisi does not have write access on this repo.

**Comment by lwasser** [comment]
Thanks @willingc i think i just fixed this. i'm new to this file but it says it's valid now. How did you even see that error!? 

<img width="1067" alt="Screenshot 2024-04-01 at 3 32 12 PM" src="https://github.com/pyOpenSci/governance/assets/7649194/ad507eea-095d-4e72-a55a-b398136059de">

**Comment by lwasser** [comment]
we are planning to overhaul this repo to turn it into a repo with 3 sections:

1. governance
2. community handbook
3. organizational handbook 

so we are just starting to sprint on this and my first task was to reboot the infrastructure!

**Comment by lwasser** [comment]
@willingc does the above mean we can close this? above meaning it says the file is valid? 
many thanks.
