### ISSUE TITLE
Review draft of our review policies and guidelines

### ISSUE THREAD

**Issue by kysolvik** [pyOpenSci/governance#6]
Hi all,

We've ported a few key sections of the rOpenSci guidebook. Could someone volunteer to review what we have so far? https://hackmd.io/XSgoe4TWQrGGbSH22eUd2Q

Once it's ready, we can move it to the dev_guide repo that @choldgraf set up for us!

Pinging some people from our last call:
@luizirber @dynamicwebpaige @mbjoseph @lwasser @choldgraf @jlpalomino

**Comment by kysolvik** [comment]
Hi all,

I'm going to port these guidelines to the dev_guide repo by the end of the week. On the next call it would be helpful to discuss some of the key content, mainly the scope and package categories. Here's a tentative list of categories we have to start, but this is definitely something we should discuss as a group. And if anyone has comments now feel free to chime in!

- **Data retrieval:** Packages for accessing and downloading data from online sources. Includes wrappers for accessing APIs.
- **Data extraction:** Packages that aid in retrieving data from unstructured sources such as text, images and PDFs.
- **Data munging:** Tools for processing data from scientific data formats.
- **Data deposition:** Tools for depositing data in scientific research repositories.
- **Data visualization:** Packages for visualizing and analyzing data. 
- **Reproducibility:** Tools to scientists ensure that their research is reproducible. E.g. version control, automated testing, or citation tools.
- **Geospatial:** Packages focused on the retrieval, manipulation, and analysis of spatial data.
- **Education:** Packages to aid with instruction and education.
- **Statistics/Machine Learning:** Packages implementing established ML or statistics methods. Note that this does not include *new* methods, only implementations of previously published algorithms.

**Comment by lwasser** [comment]
Thanks @kysolvik . i'd really love @mbjoseph feedback on accepting machine learning packages... among other feedback.

**Comment by mbjoseph** [comment]
I think this might be a good topic for a call with the group (I could go either way on whether to accept stats/ml packages).

**Comment by choldgraf** [comment]
Agree this is a good thing to get some group feedback on! The list looks like a good start!

**Comment by kysolvik** [comment]
Thanks for the input all! Discussing the scope/package categories on the next call sounds like a good plan.

In the meantime, I've moved the first parts of our dev guide to the jupyter book that @choldgraf set up. It's early days and most of the links are broken, but if you want to check it out: https://pyopensci.github.io/dev_guide/intro

**Comment by lwasser** [comment]
awesome!! thank you @kysolvik for pulling this all together. sounds like we can discuss scope at our next meeting. i'll have a look at the online materials more closely likely monday given i'm working on a proposal deadline today :)

**Comment by kysolvik** [comment]
Closing for now, but will create a new issue for feedback on our review process feedback
