### ISSUE TITLE
Review Process Feedback

### ISSUE THREAD

**Issue by kysolvik** [pyOpenSci/governance#8]
Hi there! 

This issue is to gather feedback or suggestions about our submission and review process. We are starting our first peer-reviews, so we wanted a centralized place to collect ideas. We also might create a survey for more specific feedback. We'll add the link here when that happens

**Comment by kysolvik** [comment]
Update! We now have a discourse group for pyOpenSci. That's a great place for feedback about the review process, or other discussion: https://pyopensci.discourse.group/c/review-process

**Comment by lwasser** [comment]
this issue has been mentioned a LOT but never used. so i think i will close it and possibly remove it from the template?
